// Static metadata for all 96 French metropolitan departments
// Sources: INSEE 2021 census, IGN, Wikipedia
export interface DeptInfo {
  code: string;
  nom: string;
  region: string;
  prefecture: string;
  population: number; // 2021 census
  superficie: number; // km²
  densité: number;    // inhabitants/km²
  color?: string;
}

// Search terms for DECP acheteur_nom matching
export const DEPT_SEARCH_TERMS: Record<string, string[]> = {
  "01": ["Ain", "Bourg-en-Bresse"],
  "02": ["Aisne", "Laon"],
  "03": ["Allier", "Moulins"],
  "04": ["Alpes-de-Haute-Provence", "Digne"],
  "05": ["Hautes-Alpes", "Gap"],
  "06": ["Alpes-Maritimes", "Nice", "Côte d'Azur"],
  "07": ["Ardèche", "Privas"],
  "08": ["Ardennes", "Charleville"],
  "09": ["Ariège", "Foix"],
  "10": ["Aube", "Troyes"],
  "11": ["Aude", "Carcassonne"],
  "12": ["Aveyron", "Rodez"],
  "13": ["Bouches-du-Rhône", "Marseille", "Aix-en-Provence"],
  "14": ["Calvados", "Caen"],
  "15": ["Cantal", "Aurillac"],
  "16": ["Charente", "Angoulême"],
  "17": ["Charente-Maritime", "La Rochelle", "Saintes"],
  "18": ["Cher", "Bourges"],
  "19": ["Corrèze", "Tulle"],
  "2A": ["Corse-du-Sud", "Ajaccio", "Corse"],
  "2B": ["Haute-Corse", "Bastia", "Corse"],
  "21": ["Côte-d'Or", "Dijon"],
  "22": ["Côtes-d'Armor", "Saint-Brieuc"],
  "23": ["Creuse", "Guéret"],
  "24": ["Dordogne", "Périgueux"],
  "25": ["Doubs", "Besançon"],
  "26": ["Drôme", "Valence"],
  "27": ["Eure", "Évreux"],
  "28": ["Eure-et-Loir", "Chartres"],
  "29": ["Finistère", "Quimper", "Brest"],
  "30": ["Gard", "Nîmes"],
  "31": ["Haute-Garonne", "Toulouse"],
  "32": ["Gers", "Auch"],
  "33": ["Gironde", "Bordeaux"],
  "34": ["Hérault", "Montpellier"],
  "35": ["Ille-et-Vilaine", "Rennes"],
  "36": ["Indre", "Châteauroux"],
  "37": ["Indre-et-Loire", "Tours"],
  "38": ["Isère", "Grenoble"],
  "39": ["Jura", "Lons-le-Saunier"],
  "40": ["Landes", "Mont-de-Marsan"],
  "41": ["Loir-et-Cher", "Blois"],
  "42": ["Loire", "Saint-Étienne"],
  "43": ["Haute-Loire", "Le Puy-en-Velay"],
  "44": ["Loire-Atlantique", "Nantes"],
  "45": ["Loiret", "Orléans"],
  "46": ["Lot", "Cahors"],
  "47": ["Lot-et-Garonne", "Agen"],
  "48": ["Lozère", "Mende"],
  "49": ["Maine-et-Loire", "Angers"],
  "50": ["Manche", "Saint-Lô"],
  "51": ["Marne", "Châlons-en-Champagne", "Reims"],
  "52": ["Haute-Marne", "Chaumont"],
  "53": ["Mayenne", "Laval"],
  "54": ["Meurthe-et-Moselle", "Nancy"],
  "55": ["Meuse", "Bar-le-Duc"],
  "56": ["Morbihan", "Vannes"],
  "57": ["Moselle", "Metz"],
  "58": ["Nièvre", "Nevers"],
  "59": ["Nord", "Lille", "Dunkerque"],
  "60": ["Oise", "Beauvais"],
  "61": ["Orne", "Alençon"],
  "62": ["Pas-de-Calais", "Arras", "Calais"],
  "63": ["Puy-de-Dôme", "Clermont-Ferrand"],
  "64": ["Pyrénées-Atlantiques", "Pau", "Bayonne"],
  "65": ["Hautes-Pyrénées", "Tarbes"],
  "66": ["Pyrénées-Orientales", "Perpignan"],
  "67": ["Bas-Rhin", "Strasbourg"],
  "68": ["Haut-Rhin", "Colmar", "Mulhouse"],
  "69": ["Rhône", "Lyon", "Métropole de Lyon"],
  "70": ["Haute-Saône", "Vesoul"],
  "71": ["Saône-et-Loire", "Mâcon"],
  "72": ["Sarthe", "Le Mans"],
  "73": ["Savoie", "Chambéry"],
  "74": ["Haute-Savoie", "Annecy"],
  "75": ["Paris", "Ville de Paris"],
  "76": ["Seine-Maritime", "Rouen", "Le Havre"],
  "77": ["Seine-et-Marne", "Melun"],
  "78": ["Yvelines", "Versailles"],
  "79": ["Deux-Sèvres", "Niort"],
  "80": ["Somme", "Amiens"],
  "81": ["Tarn", "Albi"],
  "82": ["Tarn-et-Garonne", "Montauban"],
  "83": ["Var", "Toulon"],
  "84": ["Vaucluse", "Avignon"],
  "85": ["Vendée", "La Roche-sur-Yon"],
  "86": ["Vienne", "Poitiers"],
  "87": ["Haute-Vienne", "Limoges"],
  "88": ["Vosges", "Épinal"],
  "89": ["Yonne", "Auxerre"],
  "90": ["Territoire de Belfort", "Belfort"],
  "91": ["Essonne", "Évry"],
  "92": ["Hauts-de-Seine", "Nanterre", "Boulogne"],
  "93": ["Seine-Saint-Denis", "Bobigny"],
  "94": ["Val-de-Marne", "Créteil"],
  "95": ["Val-d'Oise", "Cergy", "Pontoise"],
};

const DEPTS: DeptInfo[] = [
  { code: "01", nom: "Ain", region: "Auvergne-Rhône-Alpes", prefecture: "Bourg-en-Bresse", population: 659000, superficie: 5762, densité: 114 },
  { code: "02", nom: "Aisne", region: "Hauts-de-France", prefecture: "Laon", population: 527000, superficie: 7369, densité: 72 },
  { code: "03", nom: "Allier", region: "Auvergne-Rhône-Alpes", prefecture: "Moulins", population: 337000, superficie: 7340, densité: 46 },
  { code: "04", nom: "Alpes-de-Haute-Provence", region: "Provence-Alpes-Côte d'Azur", prefecture: "Digne-les-Bains", population: 165000, superficie: 6925, densité: 24 },
  { code: "05", nom: "Hautes-Alpes", region: "Provence-Alpes-Côte d'Azur", prefecture: "Gap", population: 142000, superficie: 5549, densité: 26 },
  { code: "06", nom: "Alpes-Maritimes", region: "Provence-Alpes-Côte d'Azur", prefecture: "Nice", population: 1094000, superficie: 4299, densité: 254 },
  { code: "07", nom: "Ardèche", region: "Auvergne-Rhône-Alpes", prefecture: "Privas", population: 330000, superficie: 5529, densité: 60 },
  { code: "08", nom: "Ardennes", region: "Grand Est", prefecture: "Charleville-Mézières", population: 271000, superficie: 5229, densité: 52 },
  { code: "09", nom: "Ariège", region: "Occitanie", prefecture: "Foix", population: 154000, superficie: 4890, densité: 32 },
  { code: "10", nom: "Aube", region: "Grand Est", prefecture: "Troyes", population: 310000, superficie: 6004, densité: 52 },
  { code: "11", nom: "Aude", region: "Occitanie", prefecture: "Carcassonne", population: 375000, superficie: 6139, densité: 61 },
  { code: "12", nom: "Aveyron", region: "Occitanie", prefecture: "Rodez", population: 280000, superficie: 8735, densité: 32 },
  { code: "13", nom: "Bouches-du-Rhône", region: "Provence-Alpes-Côte d'Azur", prefecture: "Marseille", population: 2052000, superficie: 5087, densité: 404 },
  { code: "14", nom: "Calvados", region: "Normandie", prefecture: "Caen", population: 693000, superficie: 5548, densité: 125 },
  { code: "15", nom: "Cantal", region: "Auvergne-Rhône-Alpes", prefecture: "Aurillac", population: 144000, superficie: 5726, densité: 25 },
  { code: "16", nom: "Charente", region: "Nouvelle-Aquitaine", prefecture: "Angoulême", population: 351000, superficie: 5956, densité: 59 },
  { code: "17", nom: "Charente-Maritime", region: "Nouvelle-Aquitaine", prefecture: "La Rochelle", population: 651000, superficie: 6864, densité: 95 },
  { code: "18", nom: "Cher", region: "Centre-Val de Loire", prefecture: "Bourges", population: 300000, superficie: 7235, densité: 41 },
  { code: "19", nom: "Corrèze", region: "Nouvelle-Aquitaine", prefecture: "Tulle", population: 241000, superficie: 5857, densité: 41 },
  { code: "2A", nom: "Corse-du-Sud", region: "Corse", prefecture: "Ajaccio", population: 160000, superficie: 4014, densité: 40 },
  { code: "2B", nom: "Haute-Corse", region: "Corse", prefecture: "Bastia", population: 185000, superficie: 4666, densité: 40 },
  { code: "21", nom: "Côte-d'Or", region: "Bourgogne-Franche-Comté", prefecture: "Dijon", population: 534000, superficie: 8763, densité: 61 },
  { code: "22", nom: "Côtes-d'Armor", region: "Bretagne", prefecture: "Saint-Brieuc", population: 601000, superficie: 6878, densité: 87 },
  { code: "23", nom: "Creuse", region: "Nouvelle-Aquitaine", prefecture: "Guéret", population: 113000, superficie: 5565, densité: 20 },
  { code: "24", nom: "Dordogne", region: "Nouvelle-Aquitaine", prefecture: "Périgueux", population: 416000, superficie: 9060, densité: 46 },
  { code: "25", nom: "Doubs", region: "Bourgogne-Franche-Comté", prefecture: "Besançon", population: 541000, superficie: 5234, densité: 103 },
  { code: "26", nom: "Drôme", region: "Auvergne-Rhône-Alpes", prefecture: "Valence", population: 520000, superficie: 6530, densité: 80 },
  { code: "27", nom: "Eure", region: "Normandie", prefecture: "Évreux", population: 597000, superficie: 6040, densité: 99 },
  { code: "28", nom: "Eure-et-Loir", region: "Centre-Val de Loire", prefecture: "Chartres", population: 432000, superficie: 5880, densité: 73 },
  { code: "29", nom: "Finistère", region: "Bretagne", prefecture: "Quimper", population: 914000, superficie: 6733, densité: 136 },
  { code: "30", nom: "Gard", region: "Occitanie", prefecture: "Nîmes", population: 747000, superficie: 5853, densité: 128 },
  { code: "31", nom: "Haute-Garonne", region: "Occitanie", prefecture: "Toulouse", population: 1416000, superficie: 6309, densité: 224 },
  { code: "32", nom: "Gers", region: "Occitanie", prefecture: "Auch", population: 191000, superficie: 6257, densité: 31 },
  { code: "33", nom: "Gironde", region: "Nouvelle-Aquitaine", prefecture: "Bordeaux", population: 1623000, superficie: 10000, densité: 162 },
  { code: "34", nom: "Hérault", region: "Occitanie", prefecture: "Montpellier", population: 1175000, superficie: 6101, densité: 193 },
  { code: "35", nom: "Ille-et-Vilaine", region: "Bretagne", prefecture: "Rennes", population: 1073000, superficie: 6775, densité: 158 },
  { code: "36", nom: "Indre", region: "Centre-Val de Loire", prefecture: "Châteauroux", population: 218000, superficie: 6791, densité: 32 },
  { code: "37", nom: "Indre-et-Loire", region: "Centre-Val de Loire", prefecture: "Tours", population: 611000, superficie: 6127, densité: 100 },
  { code: "38", nom: "Isère", region: "Auvergne-Rhône-Alpes", prefecture: "Grenoble", population: 1271000, superficie: 7431, densité: 171 },
  { code: "39", nom: "Jura", region: "Bourgogne-Franche-Comté", prefecture: "Lons-le-Saunier", population: 260000, superficie: 4999, densité: 52 },
  { code: "40", nom: "Landes", region: "Nouvelle-Aquitaine", prefecture: "Mont-de-Marsan", population: 418000, superficie: 9243, densité: 45 },
  { code: "41", nom: "Loir-et-Cher", region: "Centre-Val de Loire", prefecture: "Blois", population: 330000, superficie: 6343, densité: 52 },
  { code: "42", nom: "Loire", region: "Auvergne-Rhône-Alpes", prefecture: "Saint-Étienne", population: 762000, superficie: 4781, densité: 159 },
  { code: "43", nom: "Haute-Loire", region: "Auvergne-Rhône-Alpes", prefecture: "Le Puy-en-Velay", population: 226000, superficie: 4977, densité: 45 },
  { code: "44", nom: "Loire-Atlantique", region: "Pays de la Loire", prefecture: "Nantes", population: 1432000, superficie: 6815, densité: 210 },
  { code: "45", nom: "Loiret", region: "Centre-Val de Loire", prefecture: "Orléans", population: 677000, superficie: 6775, densité: 100 },
  { code: "46", nom: "Lot", region: "Occitanie", prefecture: "Cahors", population: 174000, superficie: 5217, densité: 33 },
  { code: "47", nom: "Lot-et-Garonne", region: "Nouvelle-Aquitaine", prefecture: "Agen", population: 331000, superficie: 5361, densité: 62 },
  { code: "48", nom: "Lozère", region: "Occitanie", prefecture: "Mende", population: 76000, superficie: 5167, densité: 15 },
  { code: "49", nom: "Maine-et-Loire", region: "Pays de la Loire", prefecture: "Angers", population: 805000, superficie: 7166, densité: 112 },
  { code: "50", nom: "Manche", region: "Normandie", prefecture: "Saint-Lô", population: 495000, superficie: 5938, densité: 83 },
  { code: "51", nom: "Marne", region: "Grand Est", prefecture: "Châlons-en-Champagne", population: 565000, superficie: 8162, densité: 69 },
  { code: "52", nom: "Haute-Marne", region: "Grand Est", prefecture: "Chaumont", population: 171000, superficie: 6211, densité: 28 },
  { code: "53", nom: "Mayenne", region: "Pays de la Loire", prefecture: "Laval", population: 308000, superficie: 5175, densité: 60 },
  { code: "54", nom: "Meurthe-et-Moselle", region: "Grand Est", prefecture: "Nancy", population: 734000, superficie: 5246, densité: 140 },
  { code: "55", nom: "Meuse", region: "Grand Est", prefecture: "Bar-le-Duc", population: 183000, superficie: 6211, densité: 29 },
  { code: "56", nom: "Morbihan", region: "Bretagne", prefecture: "Vannes", population: 760000, superficie: 6823, densité: 111 },
  { code: "57", nom: "Moselle", region: "Grand Est", prefecture: "Metz", population: 1042000, superficie: 6216, densité: 168 },
  { code: "58", nom: "Nièvre", region: "Bourgogne-Franche-Comté", prefecture: "Nevers", population: 205000, superficie: 6817, densité: 30 },
  { code: "59", nom: "Nord", region: "Hauts-de-France", prefecture: "Lille", population: 2610000, superficie: 5743, densité: 454 },
  { code: "60", nom: "Oise", region: "Hauts-de-France", prefecture: "Beauvais", population: 822000, superficie: 5860, densité: 140 },
  { code: "61", nom: "Orne", region: "Normandie", prefecture: "Alençon", population: 283000, superficie: 6103, densité: 46 },
  { code: "62", nom: "Pas-de-Calais", region: "Hauts-de-France", prefecture: "Arras", population: 1462000, superficie: 6671, densité: 219 },
  { code: "63", nom: "Puy-de-Dôme", region: "Auvergne-Rhône-Alpes", prefecture: "Clermont-Ferrand", population: 664000, superficie: 7970, densité: 83 },
  { code: "64", nom: "Pyrénées-Atlantiques", region: "Nouvelle-Aquitaine", prefecture: "Pau", population: 685000, superficie: 7645, densité: 90 },
  { code: "65", nom: "Hautes-Pyrénées", region: "Occitanie", prefecture: "Tarbes", population: 228000, superficie: 4464, densité: 51 },
  { code: "66", nom: "Pyrénées-Orientales", region: "Occitanie", prefecture: "Perpignan", population: 480000, superficie: 4116, densité: 117 },
  { code: "67", nom: "Bas-Rhin", region: "Grand Est", prefecture: "Strasbourg", population: 1138000, superficie: 4755, densité: 239 },
  { code: "68", nom: "Haut-Rhin", region: "Grand Est", prefecture: "Colmar", population: 764000, superficie: 3525, densité: 217 },
  { code: "69", nom: "Rhône", region: "Auvergne-Rhône-Alpes", prefecture: "Lyon", population: 1887000, superficie: 2715, densité: 695 },
  { code: "70", nom: "Haute-Saône", region: "Bourgogne-Franche-Comté", prefecture: "Vesoul", population: 237000, superficie: 5360, densité: 44 },
  { code: "71", nom: "Saône-et-Loire", region: "Bourgogne-Franche-Comté", prefecture: "Mâcon", population: 555000, superficie: 8575, densité: 65 },
  { code: "72", nom: "Sarthe", region: "Pays de la Loire", prefecture: "Le Mans", population: 566000, superficie: 6206, densité: 91 },
  { code: "73", nom: "Savoie", region: "Auvergne-Rhône-Alpes", prefecture: "Chambéry", population: 438000, superficie: 6028, densité: 73 },
  { code: "74", nom: "Haute-Savoie", region: "Auvergne-Rhône-Alpes", prefecture: "Annecy", population: 826000, superficie: 4388, densité: 188 },
  { code: "75", nom: "Paris", region: "Île-de-France", prefecture: "Paris", population: 2161000, superficie: 105, densité: 20600 },
  { code: "76", nom: "Seine-Maritime", region: "Normandie", prefecture: "Rouen", population: 1259000, superficie: 6278, densité: 200 },
  { code: "77", nom: "Seine-et-Marne", region: "Île-de-France", prefecture: "Melun", population: 1422000, superficie: 5915, densité: 240 },
  { code: "78", nom: "Yvelines", region: "Île-de-France", prefecture: "Versailles", population: 1438000, superficie: 2284, densité: 629 },
  { code: "79", nom: "Deux-Sèvres", region: "Nouvelle-Aquitaine", prefecture: "Niort", population: 370000, superficie: 6004, densité: 62 },
  { code: "80", nom: "Somme", region: "Hauts-de-France", prefecture: "Amiens", population: 571000, superficie: 6170, densité: 93 },
  { code: "81", nom: "Tarn", region: "Occitanie", prefecture: "Albi", population: 395000, superficie: 5758, densité: 69 },
  { code: "82", nom: "Tarn-et-Garonne", region: "Occitanie", prefecture: "Montauban", population: 260000, superficie: 3718, densité: 70 },
  { code: "83", nom: "Var", region: "Provence-Alpes-Côte d'Azur", prefecture: "Toulon", population: 1071000, superficie: 5973, densité: 179 },
  { code: "84", nom: "Vaucluse", region: "Provence-Alpes-Côte d'Azur", prefecture: "Avignon", population: 565000, superficie: 3567, densité: 158 },
  { code: "85", nom: "Vendée", region: "Pays de la Loire", prefecture: "La Roche-sur-Yon", population: 685000, superficie: 6720, densité: 102 },
  { code: "86", nom: "Vienne", region: "Nouvelle-Aquitaine", prefecture: "Poitiers", population: 436000, superficie: 6990, densité: 62 },
  { code: "87", nom: "Haute-Vienne", region: "Nouvelle-Aquitaine", prefecture: "Limoges", population: 372000, superficie: 5520, densité: 67 },
  { code: "88", nom: "Vosges", region: "Grand Est", prefecture: "Épinal", population: 361000, superficie: 5874, densité: 61 },
  { code: "89", nom: "Yonne", region: "Bourgogne-Franche-Comté", prefecture: "Auxerre", population: 337000, superficie: 7427, densité: 45 },
  { code: "90", nom: "Territoire de Belfort", region: "Bourgogne-Franche-Comté", prefecture: "Belfort", population: 143000, superficie: 609, densité: 235 },
  { code: "91", nom: "Essonne", region: "Île-de-France", prefecture: "Évry-Courcouronnes", population: 1296000, superficie: 1804, densité: 718 },
  { code: "92", nom: "Hauts-de-Seine", region: "Île-de-France", prefecture: "Nanterre", population: 1617000, superficie: 176, densité: 9188 },
  { code: "93", nom: "Seine-Saint-Denis", region: "Île-de-France", prefecture: "Bobigny", population: 1647000, superficie: 236, densité: 6979 },
  { code: "94", nom: "Val-de-Marne", region: "Île-de-France", prefecture: "Créteil", population: 1366000, superficie: 245, densité: 5575 },
  { code: "95", nom: "Val-d'Oise", region: "Île-de-France", prefecture: "Cergy-Pontoise", population: 1215000, superficie: 1246, densité: 975 },
];

const DEPT_MAP: Record<string, DeptInfo> = {};
for (const d of DEPTS) DEPT_MAP[d.code] = d;

export function getDeptInfo(code: string): DeptInfo | null {
  return DEPT_MAP[code] ?? null;
}

export function fmtPop(n: number): string {
  if (n >= 1_000_000) return (n / 1_000_000).toFixed(2).replace(".", ",") + " M hab.";
  if (n >= 1_000) return Math.round(n / 1000) + " k hab.";
  return n + " hab.";
}
